apiVersion: apps/v1
kind: Replicaset
metadata:
  name: echo
  labels:
    app: echo
spec:
  replicas: 3
  selector:
    matchLavels:
      app: echo
  template:
    metadata:
    lavels:
      app: echo
  spec:
    containers:
    - name: nginx
      image: gihyodocker/nginx-proxy:latest
      env:
      - name: BACKEND_HOST
      value: localhost:8080
      ports:
      - containerPort: 80
    - name: echo
    image: gihyodocker/nginx-proxy:latest
    ports:
      - containerPort: 8080
